version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12.19.0
        # auth:
        #   username: polarbear08
        #   password: $DOCKERHUB_PASSWORD
    resource_class: small
    steps:
      - checkout
      # - run: TOKEN=$(curl "https://auth.docker.io/token?service=registry.docker.io&scope=repository:ratelimitpreview/test:pull" | jq -r .token)
      - run: "curl -v --head -H \"Authorization: Bearer $(curl \"https://auth.docker.io/token?service=registry.docker.io&scope=repository:ratelimitpreview/test:pull\" | jq -r .token)\" https://registry-1.docker.io/v2/ratelimitpreview/test/manifests/latest 2>&1 | grep RateLimit"
