version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
        auth:
          username: polarbear08
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "hello world!"
